type PricingModel = "Free" | "Freemium" | "Paid" | "Free/Open Source";

export interface Tool {
    id: string;
    name: string;
    description: string;
    categoryId: string;
    rating: number;
    pricing: PricingModel;
    logoUrl?: string;
    link: string;
    badges?: string[];
}

export interface Category {
    id: string;
    name: string;
    icon: string;
    description: string;
    toolCount: number;
}

export const categories: Category[] = [
    {
        id: "image-gen",
        name: "Image Generation",
        icon: "🎨",
        description: "Create stunning architectural visualizations from text or sketches.",
        toolCount: 6,
    },
    {
        id: "rendering",
        name: "Rendering",
        icon: "🖼️",
        description: "Transform 3D models into photorealistic renders instantly.",
        toolCount: 4,
    },
    {
        id: "arch-specific",
        name: "Architecture-Specific",
        icon: "🏛️",
        description: "AI tools purpose-built for architectural workflows and design analysis.",
        toolCount: 6,
    },
    {
        id: "3d-gen",
        name: "3D Generation",
        icon: "🧊",
        description: "Generate 3D elements, textures, and models rapidly.",
        toolCount: 3,
    },
    {
        id: "floor-planning",
        name: "Floor Planning",
        icon: "📐",
        description: "Optimize space and layout with AI-assisted floor plan generation.",
        toolCount: 3,
    },
    {
        id: "concept-art",
        name: "Concept Art",
        icon: "✨",
        description: "Quickly iterate on initial ideas and moodboards.",
        toolCount: 4,
    },
    {
        id: "video-animation",
        name: "Video & Animation",
        icon: "🎬",
        description: "Bring your projects to life with cinematic AI motion tools.",
        toolCount: 3,
    },
    {
        id: "advanced",
        name: "Advanced Workflows",
        icon: "⚡",
        description: "Technical tools for maximum control and customization.",
        toolCount: 2,
    },
];

export const tools: Tool[] = [
    {
        id: "leonardo-ai",
        name: "Leonardo.ai",
        description: "Advanced image generation with fine-tuned architecture models and incredible stylistic control.",
        categoryId: "image-gen",
        rating: 4.8,
        pricing: "Freemium",
        link: "https://leonardo.ai",
    },
    {
        id: "midjourney",
        name: "Midjourney",
        description: "The undisputed leader in creating highly artistic, conceptual, and photorealistic architectural images.",
        categoryId: "image-gen",
        rating: 4.9,
        pricing: "Paid",
        link: "https://midjourney.com",
        badges: ["Top Rated", "$10/mo"],
    },
    {
        id: "flux",
        name: "FLUX",
        description: "High-fidelity open-source image generation model that excels at prompt adherence and realism.",
        categoryId: "image-gen",
        rating: 4.6,
        pricing: "Free/Open Source",
        link: "#",
    },
    {
        id: "dzine-ai",
        name: "Dzine.ai",
        description: "AI-powered creative assistant for quick ideation and reference imagery.",
        categoryId: "image-gen",
        rating: 4.3,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "krea",
        name: "KREA",
        description: "Real-time AI generation that updates instantly as you sketch or adjust parameters.",
        categoryId: "image-gen",
        rating: 4.4,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "stable-diffusion",
        name: "Stable Diffusion",
        description: "Versatile open-source foundation model for creating custom architectural visualization workflows.",
        categoryId: "image-gen",
        rating: 4.5,
        pricing: "Free/Open Source",
        link: "#",
    },
    {
        id: "chaos-veras",
        name: "Chaos Veras",
        description: "AI visualization plugin integrated directly into Revit, SketchUp, and Rhino.",
        categoryId: "rendering",
        rating: 4.5,
        pricing: "Paid",
        link: "#",
    },
    {
        id: "rendair-ai",
        name: "Rendair AI",
        description: "Transform simple massing models or sketches into stunning photorealistic visualizations in seconds.",
        categoryId: "rendering",
        rating: 4.6,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "rerender-ai",
        name: "ReRender AI",
        description: "Fast AI rendering engine specialized for architectural exteriors and interiors.",
        categoryId: "rendering",
        rating: 4.3,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "promeai",
        name: "PromeAI",
        description: "Comprehensive suite for turning sketches into realistic renders and generating detailed floor plans.",
        categoryId: "arch-specific",
        rating: 4.5,
        pricing: "Freemium",
        link: "#",
        badges: ["Popular"],
    },
    {
        id: "architectgpt",
        name: "ArchitectGPT",
        description: "AI design assistant focusing on residential architecture and site analysis.",
        categoryId: "arch-specific",
        rating: 4.2,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "archistar",
        name: "Archistar",
        description: "Parametric design and generative zoning tool for rapid site feasibility studies.",
        categoryId: "arch-specific",
        rating: 4.3,
        pricing: "Paid",
        link: "#",
    },
    {
        id: "testfit",
        name: "TestFit",
        description: "Real estate feasibility platform utilizing generative design algorithms for instant high-density routing.",
        categoryId: "arch-specific",
        rating: 4.4,
        pricing: "Paid",
        link: "#",
    },
    {
        id: "myarchitectai",
        name: "MyArchitectAI",
        description: "AI-driven drafting and conceptual design aid for small to medium-sized practices.",
        categoryId: "arch-specific",
        rating: 4.1,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "archivinci",
        name: "ArchiVinci",
        description: "Specialized tool for converting conceptual line art into varied architectural styles.",
        categoryId: "arch-specific",
        rating: 4.0,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "mnml-ai",
        name: "mnml.ai",
        description: "AI platform focusing on minimalist, clean architectural aesthetic rendering.",
        categoryId: "arch-specific",
        rating: 4.2,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "meshy-ai",
        name: "Meshy.ai",
        description: "Innovative platform for generating 3D assets and textures rapidly from text or image inputs.",
        categoryId: "3d-gen",
        rating: 4.4,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "3d-ai-studio",
        name: "3D AI Studio",
        description: "Generate 3D models and environments directly from descriptive text prompts.",
        categoryId: "3d-gen",
        rating: 4.2,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "kaedim",
        name: "Kaedim",
        description: "Machine learning software that turns 2D images into production-ready 3D models.",
        categoryId: "3d-gen",
        rating: 4.3,
        pricing: "Paid",
        link: "#",
    },
    {
        id: "maket-ai",
        name: "Maket.ai",
        description: "Generative platform focusing on rapid residential floor plan layout and massing generation.",
        categoryId: "floor-planning",
        rating: 4.3,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "coohom",
        name: "Coohom",
        description: "Powerful interior design and floor planning software with strong AI-assisted rendering capabilities.",
        categoryId: "floor-planning",
        rating: 4.4,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "comfyui",
        name: "ComfyUI",
        description: "The most powerful, node-based graphical user interface for Stable Diffusion, offering unparalleled workflow control.",
        categoryId: "advanced",
        rating: 4.7,
        pricing: "Free/Open Source",
        link: "#",
        badges: ["Expert Choice"],
    },
    {
        id: "kling-ai",
        name: "Kling AI",
        description: "High-quality AI video generator capable of producing realistic architectural fly-throughs from text.",
        categoryId: "video-animation",
        rating: 4.5,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "luma-dream-machine",
        name: "Luma Dream Machine",
        description: "Fast, high-quality video generation model excellent for bringing architectural still renders to life.",
        categoryId: "video-animation",
        rating: 4.4,
        pricing: "Freemium",
        link: "#",
    },
    {
        id: "nim-video",
        name: "Nim.video",
        description: "AI-driven animation platform for stylized and conceptual motion graphics.",
        categoryId: "video-animation",
        rating: 4.2,
        pricing: "Freemium",
        link: "#",
    },
];
